### ISSUE TITLE
Please provide an example using Aggregation Query

### ISSUE THREAD

**Issue by punkdata** [EqualExperts/mongo-shell-like-query#4]
I've been trying to use this library to perform an aggregation query but I'm having difficulty doing so.  Could you provide an example of how to execute an aggregation query using $match & $projection in java?

**Comment by mrugenmike** [comment]
Hello, please see the test here for a basic example of Mongo Aggregation:
https://github.com/EqualExperts/mongo-shell-like-query/blob/master/src/test/scala/com/ee/dynamicmongoquery/MongoQueryParserTest.scala#L152

Though the test is in Scala, it is quite self explanatory.
